"""Reviewed canonical register contracts; source-specific mappings are never assumed."""
BRANCHES={'dadri':'Dadri','vaishali':'Vaishali','sikandrabad':'Sikandrabad','meerut':'Meerut Road, Ghaziabad'}
ROLES=['management','finance','collections','procurement','reviewer']
MASTER_TYPES=['entity','branch','department','cost_centre','panel','vendor','bank_account','category','account','employee','consultant']
ACCOUNT_CATEGORIES=['revenue','direct_cost','operating_expense','depreciation','finance_cost','tax','asset','cash','liability','equity']
COMMON={'doc_id':'Stable document / line ID','entity_id':'Legal entity key','branch_id':'Branch key','date':'Posting / document date','amount':'Signed amount ₹','department_id':'Department key','cost_centre_id':'Cost centre key','panel_id':'Panel key','vendor_id':'Vendor key','status':'Status','notes':'Notes / source interpretation'}
# Type-specific financial meaning is explicit; raw source columns must be mapped into these fields.
TYPES={
 'journal':('Accounting journal','Accounting','doc_id date entity_id branch_id voucher_id account_id debit credit',{'voucher_id':'Accounting voucher ID','account_id':'Ledger account key','debit':'Debit ₹ (zero is explicit)','credit':'Credit ₹ (zero is explicit)'}),
 'opening_balance':('Opening account balance','Accounting','doc_id date entity_id branch_id account_id amount',{'account_id':'Ledger account key'}),
 'trial_balance':('Trial balance snapshot','Accounting','doc_id date entity_id branch_id account_id opening_debit opening_credit movement_debit movement_credit closing_debit closing_credit',{'account_id':'Ledger account key','opening_debit':'Opening debit','opening_credit':'Opening credit','movement_debit':'Period debit movement','movement_credit':'Period credit movement','closing_debit':'Closing debit','closing_credit':'Closing credit','period_start':'Movement-period start'}),
 'billing':('Patient bill / discharge','Revenue','doc_id date entity_id branch_id bill_id uhid admission_id amount',{'bill_id':'Bill ID','uhid':'UHID (string)','admission_id':'Admission / IPD ID','patient':'Patient display name','admission_date':'Admission date','discharge_date':'Discharge date','gross':'Gross billed ₹','discount':'Discount ₹','care_setting':'Validated OPD/IPD/emergency/daycare','doctor_id':'Consultant key','credit_revenue':'Verified credit revenue yes/no','pharmacy_included':'Pharmacy included yes/no/unknown','approved_discount':'Discount approval evidence','due_date':'Contractual due date','package_id':'Package identifier','tariff_id':'Approved tariff key'}),
 'service':('Service activity','Revenue','doc_id date entity_id branch_id description',{'service_id':'Service line ID','bill_id':'Linked bill ID','uhid':'UHID','admission_id':'Admission ID','description':'Service description','code':'Service code','quantity':'Validated service units','amount':'Attributable net service charge (null for package activity)','actual_cost':'Recorded actual cost amount','expected_bill':'Billing expected yes/no','performed':'Performed yes/no','tariff_id':'Approved tariff key'}),
 'encounter':('Encounter / bed-day activity','Revenue','doc_id date entity_id branch_id admission_id',{'uhid':'UHID','admission_id':'Admission ID','discharge_date':'Discharged date','occupied_bed_days':'Occupied bed-days','available_bed_days':'Available bed-days','lead_id':'Verified marketing lead ID'}),
 'pharmacy':('Pharmacy sale / return','Inventory','doc_id date entity_id branch_id amount item_id',{'bill_id':'Bill ID','item_id':'Medicine key','description':'Medicine','quantity':'Signed sold quantity','actual_cost':'Validated signed COGS amount','pharmacy_source':'Main/Secondary','batch_id':'Batch key'}),
 'claim':('Claim lifecycle event','Receivables','doc_id date entity_id branch_id claim_id bill_id event',{'claim_id':'Claim ID','bill_id':'Bill ID','event':'ready/submitted/query/response/approved/rejected/appealed/resubmitted/expected','approved_amount':'Approved claim amount (not receipt)','deduction':'Deduction ₹ (informational unless explicit adjustment)','reason':'Deduction/query reason','expected_date':'Expected collection date','due_date':'Contractual payment due date','owner':'Responsible owner','next_action':'Next action'}),
 'receipt':('Receipt / patient advance / refund','Receivables','doc_id date entity_id branch_id amount',{'receipt_id':'Receipt ID','bank_account_id':'Bank/cash account key','receipt_type':'collection/advance/refund/loan/transfer','reference':'Bank reference','original_receipt_id':'Original receipt for authorised refund','authorisation':'Refund authorisation','patient':'Patient or payer'}),
 'ar_adjustment':('Receivable credit / write-off / opening','Receivables','doc_id date entity_id branch_id bill_id amount adjustment_type',{'bill_id':'Bill ID (OPENING for opening)','adjustment_type':'opening/credit/writeoff/reversal','already_in_bill':'Already reflected in bill net yes/no','authorisation':'Approval evidence'}),
 'purchase_order':('Purchase order','Payables','doc_id date entity_id branch_id po_id vendor_id amount',{'po_id':'PO ID','item_id':'Item key','quantity':'Ordered quantity','rate':'Approved rate','due_date':'Expected receipt date'}),
 'goods_receipt':('Goods receipt','Payables','doc_id date entity_id branch_id grn_id po_id vendor_id',{'grn_id':'Goods receipt ID','po_id':'PO ID','item_id':'Item key','quantity':'Received quantity','rate':'Received rate'}),
 'invoice':('Vendor invoice','Payables','doc_id date entity_id branch_id invoice_id vendor_id amount',{'invoice_id':'Invoice ID','po_id':'PO ID','grn_id':'GRN ID','item_id':'Item key','quantity':'Invoiced quantity','rate':'Invoice rate','due_date':'Due date','disputed':'Disputed yes/no','critical':'Clinical criticality yes/no','retention':'Retention ₹','category_id':'Purchase category key'}),
 'payment':('Payment / vendor advance','Payables','doc_id date entity_id branch_id amount',{'payment_id':'Payment ID','bank_account_id':'Bank/cash account key','payment_type':'settlement/advance/refund/transfer/principal/interest','reference':'Bank reference','original_payment_id':'Original payment ID'}),
 'ap_adjustment':('Vendor credit / opening / reversal','Payables','doc_id date entity_id branch_id invoice_id vendor_id amount adjustment_type',{'invoice_id':'Invoice ID (OPENING for opening)','adjustment_type':'opening/credit/reversal','already_in_invoice':'Already in invoice net yes/no'}),
 'bank':('Bank statement movement / balance','Treasury','doc_id date entity_id branch_id bank_account_id entry_type',{'bank_account_id':'Bank account key','entry_type':'movement/opening/closing/cash_count','amount':'Signed deposit + / withdrawal − or balance ₹','reference':'Bank transaction reference','movement_type':'collection/payment/transfer/principal/interest/charge','bank_transaction_id':'Bank transaction ID'}),
 'cashbook':('Book cash / bank movement','Treasury','doc_id date entity_id branch_id bank_account_id amount',{'bank_account_id':'Cash/bank account key','reference':'Book reference','movement_type':'collection/payment/transfer/loan/principal/interest/charge','book_transaction_id':'Book transaction ID','entry_type':'movement/opening'}),
 'expense':('Incurred expense / accrual','Expenses','doc_id date entity_id branch_id amount category_id',{'category_id':'Expense head key','invoice_id':'Linked vendor invoice (prevents duplicate forecast)','actual_cost':'Recorded actual cost','employee_id':'Employee/consultant key','due_date':'Due date','evidence':'Receipt/contract evidence'}),
 'payroll':('Payroll / reimbursement','Expenses','doc_id date entity_id branch_id amount employee_id',{'employee_id':'Employee/consultant key','payroll_type':'salary/benefit/reimbursement','due_date':'Due date','contract_id':'Contract key','evidence':'Payroll evidence','invoice_id':'Linked invoice if already in payable schedule'}),
 'consultant':('Consultant payout record','Expenses','doc_id date entity_id branch_id consultant_id amount',{'consultant_id':'Consultant key','contract_id':'Contract key','base_amount':'Verified defined contract base ₹','base_kind':'billed/collected/procedure','quantity':'Procedure quantity','exclusions':'Excluded base ₹','deductions':'Contract deduction ₹','due_date':'Due date','evidence':'Contract/base evidence','invoice_id':'Linked invoice if in payable schedule'}),
 'inventory':('Inventory receipt / issue / count','Inventory','doc_id date entity_id branch_id item_id movement_type quantity',{'item_id':'Item key','store_id':'Store key','batch_id':'Batch key','movement_type':'opening/receipt/issue/sale/return/transfer_in/transfer_out/adjustment/count','quantity':'Signed movement; count is absolute','actual_cost':'Validated signed inventory value movement','unit_cost':'Recorded unit cost (informational)','expiry_date':'Batch expiry','transfer_id':'Matched transfer ID','bill_id':'Charge reference','billing_expected':'Billing expected yes/no','valuation_method':'Validated recorded-cost method'}),
 'asset':('Asset register / capex','Assets','doc_id date entity_id branch_id asset_id amount',{'asset_id':'Asset ID','category_id':'Asset category','purchase_date':'Purchase date','commission_date':'Commissioning date','useful_life_months':'Approved useful life months','accumulated_depreciation':'Recorded accumulated depreciation','residual_value':'Approved residual value','depreciation_policy':'recorded/straight_line','disposed_date':'Disposal date','approved_budget':'Approved capex budget ₹','committed_amount':'Committed capex ₹','maintenance':'Maintenance information'}),
 'loan':('Loan movement / schedule','Assets','doc_id date entity_id branch_id loan_id event amount',{'loan_id':'Loan ID','event':'opening/drawdown/principal/interest/fee/scheduled_principal/scheduled_interest','due_date':'Repayment due date','security':'Security details','covenant':'User-entered covenant (no inferred check)','paid_doc_id':'Payment reference'}),
 'budget':('Monthly budget / forecast','Budget','doc_id date entity_id branch_id category_id amount budget_type',{'category_id':'Account/category key','budget_type':'revenue/expense/capex','month':'YYYY-MM','owner':'Budget owner','comment':'Action comment','approved':'Approved yes/no'}),
 'commitment':('Approved payment commitment','Treasury','doc_id date entity_id branch_id amount due_date',{'due_date':'Expected payment date','invoice_id':'Linked invoice; avoids forecast duplication','category_id':'Head','approved':'Approved yes/no','direction':'outflow/inflow'}),
 'forecast_assumption':('Cash forecast assumption','Budget','doc_id date entity_id branch_id amount due_date direction',{'due_date':'Expected cash date','direction':'inflow/outflow','linked_doc_id':'Linked obligation ID (do not duplicate)','scenario':'base/delayed/stress','owner':'Assumption owner'}),
 'finance_scenario':('Hospital economics scenario','Budget','doc_id date entity_id branch_id scenario_name',{'scenario_name':'Scenario name','patient_volume':'Assumed patient/admission volume','price_per_patient':'Assumed net price ₹ per patient','deduction_percent':'Assumed deduction %','variable_cost_per_patient':'Assumed direct consumption cost per patient','fixed_operating_cost':'Assumed fixed operating expense ₹','payroll_cost':'Assumed payroll ₹','consultant_cost':'Assumed consultant expense ₹','consumption_cost':'Assumed other consumption expense ₹ (not purchases)','collection_percent':'Assumed cash collection %','inventory_purchase_cash':'Assumed inventory purchase cash outflow ₹','capex_cash':'Assumed capex cash outflow ₹','loan_drawdown':'Assumed loan cash inflow ₹','principal_repayment':'Assumed principal cash outflow ₹','interest_cost':'Assumed interest expense ₹','capacity_bed_days':'Assumed available bed-days','occupied_bed_days':'Assumed occupied bed-days','owner':'Scenario owner'}),
 'statutory':('Statutory liability / payment','Statutory','doc_id date entity_id branch_id liability_id event amount',{'liability_id':'Liability ID','event':'liability/payment/credit','category_id':'GST/TDS/PF/ESI/other approved category','due_date':'User-approved due date','challan':'Payment challan/reference','evidence':'Supporting evidence','tax_treatment':'Approved treatment (no legal defaults)'}),
 'related_party':('Related-party / interbranch record','Accounting','doc_id date entity_id branch_id counterparty_branch amount',{'counterparty_branch':'Counterparty branch','counterparty_entity':'Counterparty entity','reference':'Counterpart reference','account_id':'Account key','elimination_group':'Reviewed counterpart group'}),
}
NUMBERS={'amount','debit','credit','opening_debit','opening_credit','movement_debit','movement_credit','closing_debit','closing_credit','gross','discount','actual_cost','quantity','rate','approved_amount','deduction','retention','base_amount','exclusions','deductions','occupied_bed_days','available_bed_days','unit_cost','accumulated_depreciation','residual_value','approved_budget','committed_amount','useful_life_months','patient_volume','price_per_patient','deduction_percent','variable_cost_per_patient','fixed_operating_cost','payroll_cost','consultant_cost','consumption_cost','collection_percent','inventory_purchase_cash','capex_cash','loan_drawdown','principal_repayment','interest_cost','capacity_bed_days'}
DATE_FIELDS={'date','admission_date','discharge_date','due_date','expected_date','expiry_date','purchase_date','commission_date','disposed_date','period_start'}
READ_SECTIONS={'management':None,'finance':None,'collections':{'Revenue','Receivables'},'procurement':{'Payables','Inventory'},'reviewer':{'Accounting','Revenue','Receivables','Payables','Treasury','Inventory','Assets','Budget','Statutory'}}

def fields(kind): return dict(COMMON,**TYPES[kind][3])
def readable(role,kind): return READ_SECTIONS[role] is None or TYPES[kind][1] in READ_SECTIONS[role]
